---
- hosts: k8s
  roles:
    - role: docker
      become: yes

    - role: kubernetes
      become: yes

- hosts: master
  roles:
    - role: master
      become: yes

- hosts: worker
  roles:
    - role: workers
      become: yes
